name: WebGL Build

on:
  workflow_dispatch: {}
  workflow_call:
    # 呼び出し元にアーティファクト名を返す設定
    outputs:
      artifact_name:
        description: "The name of the build artifact"
        value: ${{ jobs.build.outputs.artifact_name }}
    # 呼び出し元からシークレットを受け取る設定
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

jobs:
  build:
    name: Run the WebGL build
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}

    steps:
      # 仮想環境にクローン
      - name: Check out my unity project.
        uses: actions/checkout@v4
        with:
          lfs: true

      # ビルドファイルに使うHashを変数へ
      - name: Set outputs
        id: vars
        run: echo "ARTIFACT_NAME=WebGL-Build-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 次の起動時の高速化のためライブラリをキャッシュ
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: |
            Library/PackageCache
            Library/ScriptAssemblies
            Library/Bee
            Library/ShaderCache
          key: Library-${{ hashFiles('Packages/packages-lock.json', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run the WebGL build
        uses: game-ci/unity-builder@v4
        env:
          # 受け取ったシークレットを使う
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL

      - name: Upload the WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build
