name: Create GitHub Release Note

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        description: 'Build artifact name to download'
        required: true
        type: string

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Set env variables
        run: |
          echo "ARTIFACT_NAME=${{ inputs.ARTIFACT_NAME }}" >> $GITHUB_ENV
          branch_name="${{ github.event.pull_request.head.ref }}"
          version_tag=$(echo "${branch_name}" | sed 's/release\///')
          echo "VERSION_TAG=${version_tag}" >> $GITHUB_ENV
          echo "ZIP_FILE_NAME=${{ github.event.repository.name }}-${version_tag}.zip" >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Zip build files
        run: zip -r ${{ env.ZIP_FILE_NAME }} ./${{ env.ARTIFACT_NAME }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Release ${{ env.VERSION_TAG }}
          generate_release_notes: true
          files: ./${{ env.ZIP_FILE_NAME }}
