name: GitHub Event Handler

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  init:
    name: Check conditions and Set version variables
    runs-on: ubuntu-latest
    # PRがマージ、ブランチ名がrelease/*
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/') == true

    # release/のあとをversion_tagとして出力
    outputs:
      version_tag: ${{ steps.var.outputs.version_tag }}

    steps:
      - id: var
        run: |
          branch_name="${{ github.event.pull_request.head.ref }}"
          echo 'version_tag=$(echo "${branch_name}" | sed 's/release\///')' >> $GITHUB_OUTPUT

  # labelがrelease/Windowの時実行行
  call_release_windows_to_github:
    name: Call release Windows build to GitHub
    needs: init
    if: >
      contains(github.event.pull_request.labels.*.name, 'release/Windows')
    # uses: ./.github/workflows/release-github.yml
    # with:
    #   build_target_name: Windows
    #   version_tag: ${{ needs.init.outputs.version_tag }}
    steps:
      - run: echo windows

  # labelがrelease/WebGLの時実行
  call_release_webgl_to_netlify:
    name: Call release WebGL build to Netlify
    needs: init
    if: >
      contains(github.event.pull_request.labels.*.name, 'release/WebGL')
    # uses: ./.github/workflows/release-netlify.yml
    # with:
    #   version_tag: ${{ needs.init.outputs.version_tag }}
    steps:
      - run: echo webgl
