name: GitHub Event Handler

on:
  pull_request:
    branches:
      - main
    types: [closed]

# labelにrelease/Windowsとrelease/WebGLがついてたら両方通る
# ブランチ名がrelease/*だったら、*をタグにする
# じゃなければ、ブランチ名がそのままタグになる
jobs:
  init:
    name: Check conditions and Set version variables
    runs-on: ubuntu-latest
    # PRがマージ、labelがrelease/*
    if: >
      github.event.pull_request.merged == true &&
      ( contains(github.event.pull_request.labels.*.name, 'release/Windows') ||
        contains(github.event.pull_request.labels.*.name, 'release/WebGL') )

    outputs:
      version_tag: ${{ steps.var.outputs.version_tag }}

    steps:
      - name: check_env
        # シークレットの値を環境変数として定義
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

        run: |
          isError=false

          # シェルスクリプト内では、定義した環境変数名（$UNITY_EMAIL）を参照します
          # [ -z "$VAR" ] は「変数が空である」ことをチェック
          if [ -z "$UNITY_EMAIL" ]; then
            echo "::error::UNITY_EMAILが設定されていません"
            isError=true
          fi

          if [ -z "$UNITY_PASSWORD" ]; then
            echo "::error::UNITY_PASSWORDが設定されていません"
            isError=true
          fi

          if [ -z "$UNITY_LICENSE" ]; then
            echo "::error::UNITY_LICENSEが設定されていません"
            isError=true
          fi

          if $isError ; then
            exit 1
          fi

      - name: Set version tag
        id: var
        # version_tag = ブランチ名がrelease/*の場合その後を使い、それ以外はそのまま
        run: |
          branch_name="${{ github.event.pull_request.head.ref }}"
          if [[ "${branch_name}" == release/* ]]; then
            version_tag=$(echo "${branch_name}" | sed 's/release\///')
          else
            version_tag="${branch_name}"
          fi
          echo "version_tag=${version_tag}" >> $GITHUB_OUTPUT

  # labelがrelease/Windowの時実行
  call_release_windows_to_github:
    name: Call release Windows build to GitHub
    needs: init
    if: >
      contains(github.event.pull_request.labels.*.name, 'release/Windows')
    uses: ./.github/workflows/release-github.yml
    secrets: inherit
    with:
      build_target_name: Windows
      version_tag: ${{ needs.init.outputs.version_tag }}

  # labelがrelease/WebGLの時実行
  call_release_webgl_to_netlify:
    name: Call release WebGL build to Netlify
    needs: init
    if: >
      contains(github.event.pull_request.labels.*.name, 'release/WebGL')
    uses: ./.github/workflows/release-netlify.yml
    secrets: inherit
    with:
      version_tag: ${{ needs.init.outputs.version_tag }}
