name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create_release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')

    steps:
      - name: Call build workflow
        uses: ./.github/workflows/build-windows.yml
        secrets: inherit

      - name: Prepare environment variables
        id: prepare
        run: |
          echo "ZIP_FILE_NAME=${{ github.event.repository.name }}-${{ github.event.pull_request.head.ref }}.zip" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=build_artifact" >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Zip build files
        run: zip -r ${{ env.ZIP_FILE_NAME }} ./${{ env.ARTIFACT_NAME }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          generate_release_notes: true

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ZIP_FILE_NAME }}
          asset_name: ${{ env.ZIP_FILE_NAME }}
          asset_content_type: application/zip
