name: Release WebGL To Netlify

on:
  workflow_dispatch: {}
  # pull_request:
  #   branches:
  #     - main
  #   types: [closed]

jobs:
  call_build_webgl:
    name: Build
    # if: >
    #   github.event.pull_request.merged == true &&
    #   contains(github.event.pull_request.labels.*.name, 'release')
    uses: ./.github/workflows/build-unity.yml
    secrets: inherit
    with:
      build_target_name: WebGL

  deploy:
    name: Deploy to Netlify
    needs: call_build_webgl
    uses: ./.github/workflows/upload-build-to-repo.yml
    secrets: inherit
    with:
      artifact_name: ${{ needs.call_build_webgl.outputs.artifact_name }}
      repository_path: epen3420/epen_page
