name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  call_build:
    name: Build (Windows)
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    uses: ./.github/workflows/build-windows.yml # ここを書き換えればビルドのメソッドを変えられる
    secrets: inherit

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: call_build

    env:
      ZIP_FILE_NAME: ${{ github.event.repository.name }}-${{ github.run_number }}.zip
      ARTIFACT_NAME: ${{ needs.call_build.outputs.artifact_name }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}

      - name: Zip build files
        run: zip -r ${{ env.ZIP_FILE_NAME }} ./${{ env.ARTIFACT_NAME }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          generate_release_notes: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ZIP_FILE_NAME }}
          asset_name: ${{ env.ZIP_FILE_NAME }}
          asset_content_type: application/zip
