name: Deploy to GitHub Pages

on:
  workflow_call:
    outputs:
      url:
        value: ${{ jobs.deploy.deployment.outputs.page_url }}

  workflow_dispatch: {}


jobs:
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2

        - run: |
            echo ${{ steps.deployment.outputs.page_url }}
