name: Test

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to Netlify
    uses: ./.github/workflows/upload-build-to-repo.yml
    with:
      artifact_name: WebGL-Build-ea9bd5d
      repository_path: epen3420/epen_page
